# Generated by Django 4.1.1 on 2022-10-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrivia', '0002_cuestionariosociales_cuestionariotecnologia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pwd',
        ),
    ]
